### ISSUE TITLE
refactoring within whole project

### ISSUE THREAD

**Issue by schlichtanders** [hax/refactor#12]
It would be great to have a plugin which handles renaming/refactoring on project level
Is this possible already with this plugin? or maybe not intended at all?

**Comment by przezor** [comment]
:+1:  Are there any plans for that? :)

**Comment by tusharmath** [comment]
Yup, seriously.

**Comment by PhiLhoSoft** [comment]
IMHO, it is nearly impossible to do that (in a reliable way) in JavaScript. For example, you rename a `process()` method in a class / module / object, but you probably have no way to know if an occurrence of `process()` belongs to this entity or to another that happens to use the same name...

In other (statically typed) languages, that would need to maintain a database of symbols with their hierarchy... At least, in these languages, we know the type, hence the methods / fields, of each variable.

An alternative would be to search for the identifier across the project (should include strings with the identifier only) and to let the user to tell for each occurrence if it should be renamed or not.

**Comment by tusharmath** [comment]
Webstorm does an amazing job with that.

**Comment by PhiLhoSoft** [comment]
Sure, and they have a (big?) team of full-time employees to work on the feature... :smile: 
But at least, it shows it might be possible.

I briefly used WebStorm (for the trial period...), I don't recall using the feature. Do you care to describe how it works (or to give a link to a page describing it)?

**Comment by tusharmath** [comment]
There you go — https://www.jetbrains.com/webstorm/help/refactoring-source-code.html
Features include —
- Copy/Clone
- Move
- Rename
- Safe Delete
- Extract Method
- Inline
- Extract Variable
- Extract Variable for Sass
- Change Signature in JavaScript
- Extract Parameter in JavaScript
- Extract Variable in JavaScript

That is the reason, why I have permanently shifted to Webstorm — Amazing refactoring capabilities!

I don't mind working on this project because I find webstorm otherwise very clunky and prefer Atom.

**Comment by henrikrudstrom** [comment]
has anyone looked into [GraspJS](http://www.graspjs.com/) it does refactoring on the AST. I ended up here when i was looking for an atom integration...

**Comment by PhiLhoSoft** [comment]
I didn't know the tool. Looks very interesting. Note that there are other libraries producing an AST, eg. Esprima used by ESLint, and some others. You can find a relatively comprehensive list in http://astexplorer.net/

**Comment by hax** [comment]
This project is only for renaming the symbols in the scope (js-refactor plugin support function scope, block scope, or module scope). It's very hard to deal with cross-modules renaming. You should use full fledged IDE for such tasks.
