### ISSUE TITLE
ctrl-alt-r for mac

### ISSUE THREAD

**Issue by RicardoGeek** [hax/refactor#17]
the shortcut: `ctrl-alt-r`
is not working for mac os :disappointed: 
it should map to `control+option+r`

**Comment by nerdpad** [comment]
Does this work on mac at all?

**Comment by ghost** [comment]
@NerdPad It does not work on Mac at all (OS X El Capitan, Atom 1.8.0).

**Comment by hax** [comment]
Closed. Further discussion of keybinding issues could goto #22 .
