### ISSUE TITLE
Oddly breaks icons when enabled...

### ISSUE THREAD

**Issue by kentcdodds** [hax/refactor#23]
I'm not sure what could possibly be causing this, but when I enable this plugin, sometimes my icons stop working. For example:

<img width="590" alt="screen shot 2016-07-05 at 8 23 49 pm" src="https://cloud.githubusercontent.com/assets/1500684/16605673/6cee9fe6-42ee-11e6-9348-878895a8bc23.png">

You'll notice the icons are all just squares. If I disable the refactor plugin, then the icons work again:

<img width="1224" alt="screen shot 2016-07-05 at 8 24 36 pm" src="https://cloud.githubusercontent.com/assets/1500684/16605687/88ec49f0-42ee-11e6-8fcc-def99dc9154b.png">

Any ideas?

**Comment by hax** [comment]
It's weird... I will investigate it.

**Comment by TimeWanderer** [comment]
Any updates on this?

**Comment by PurpleMagick** [comment]
Still getting the problem after the update to 0.10.0 if both this plugin and **js-refactor** are enabled. I tried disabling everything else but those two and it seems consitent.

**Comment by RB-Lab** [comment]
Confirm. Refactor 0.10.0, js-refactor 0.7.3; problem still there...

**Comment by patrickhulce** [comment]
I'm also experiencing this problem

Atom: 1.12.6
Refactor: 0.11.1
js-refactor: 0.7.3

![screen shot 2016-11-30 at 4 14 57 pm](https://cloud.githubusercontent.com/assets/2301202/20776915/4eae7d00-b718-11e6-8191-a9999d6cfdcb.png)

**Comment by patrickhulce** [comment]
@hax FYI this seems to happen because all the requests (including the fonts that enable the icons) in Network panel show up as 'Cancelled' when this happens and it seems to be js-refactor that's the culprit in my case not just refactor (or just coincidence of my enabling cycle)

![image](https://cloud.githubusercontent.com/assets/2301202/20873908/822b3852-ba61-11e6-9df9-64b66133ba8f.png)

**Comment by caesar** [comment]
Same issue here. I'm using it with `js-refactor` so not sure which is causing the problem – disabling either fixes it.

**Comment by patrickhulce** [comment]
Also related https://discuss.atom.io/t/all-icons-fail-to-load-on-startup/31889/8

**Comment by sgsvnk** [comment]
This issue has been there for quite some time and is being investigated. I was hoping a resolution in the recent release, but there isn't any. Same issue again with the recent update. 

More Info on this issue at [[1]](https://github.com/hax/refactor/pull/28) and [[2]](https://github.com/hax/js-refactor/issues/18).

**Comment by kentcdodds** [comment]
I'm not using this project anymore, so I'll go ahead and close this :)

**Comment by kentcdodds** [comment]
FWIW, I was unable to reproduce the issue anymore and now it seems that it's simply not working 🤷‍♂️
