### ISSUE TITLE
Problem with proto

### ISSUE THREAD

**Issue by falkowski-os** [hax/refactor#24]
Hi, When I try do refactor method `Document.prototype.initButtons` to src was added chars and this method isn't highlight in other place
`Document.prototype.initButtons = function () {
    "use strict";
    this.setButtonEnable("prevPage", false);
....
}`

**Comment by hax** [comment]
This issue belongs to https://github.com/hax/js-refactor , and js-refactor only support refactoring of local variable. It's hard to track member properties/methods, especially in dynamic language like js.
