### ISSUE TITLE
Disable overriding of selection highlight color

### ISSUE THREAD

**Issue by sgsvnk** [hax/refactor#25]
Option to disable overriding the colour of selection highlighting. 

![image](https://cloud.githubusercontent.com/assets/4642729/17641658/e72f5d10-6146-11e6-918a-2a3594088c92.png)

It is important that the user preference to select the text should not be overridden by an operation that is not intended anymore.

**Comment by hax** [comment]
The default styles of latest version has changed to colored underlines. So it seems you (or some other plugins) wrote some custom styles.

**Comment by sgsvnk** [comment]
Even if it custom, shouldn't the selection be given more importance than argument selection when multiple arguments are selected? And underlines, would still come on top of selection colors right?

**Comment by hax** [comment]
@sgsvenkatesh Refactor just add some [decorations](https://atom.io/docs/api/v1.9.8/Decoration) for symbols, it depends on Atom itself to deal with the render effect of selections and decorations.

**Comment by hax** [comment]
Close old issue.
