### ISSUE TITLE
Rename not working 

### ISSUE THREAD

**Issue by zaaack** [hax/refactor#29]
Hightlight is working, but either rename shortcuts or commands are not working.

**Comment by gerard2perez** [comment]
I'm working on windows and it does nothing...

**Comment by thisdotrob** [comment]
Same here. On OSX with latest stable Atom. Shortcuts and commands not working

**Comment by deed02392** [comment]
Came here as it's also not working here, latest Atom Windows x64.

**Comment by zaaack** [comment]
Hi, everyone, I got sometime to debug this package recently, and find out the reason why not working.

Looks like after the atom upgraded, the coffee compiler works a little different and cause the old way to iterate a Set is not working. 

I just change the loop in https://github.com/hax/refactor/blob/master/lib/refactor.coffee#L59 and the problem is fixed.

``` coffee
  onRename: (e) =>
    isExecuted = false
    for watcher in Array.from @watchers
      isExecuted or= watcher.rename()
    d 'rename', isExecuted
    return if isExecuted
    e.abortKeyBinding()

  onDone: (e) =>
    isExecuted = false
    for watcher in Array.from @watchers
      isExecuted or= watcher.done()
    return if isExecuted
    e.abortKeyBinding()
```

Here is the pr: https://github.com/hax/refactor/pull/30

**Comment by sgsvnk** [comment]
@zaaack This perfectly solved the problem. Hope this will be merged and released soon.
