### ISSUE TITLE
Package.activateConfig is deprecated.

### ISSUE THREAD

**Issue by azat-co** [hax/refactor#3]
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details

```
Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:265:11)
Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:236:14)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
```

**Comment by imevro** [comment]
Anyone?

**Comment by imevro** [comment]
It isn't working and it really bad.

@hax @minodisk @seriema

**Comment by seriema** [comment]
@theaqua can you be a bit more specific? =) If it isn't this exact issue, feel free to create a new issue. (I'm not officially affiliated in any way, I just did some PR's)

**Comment by imevro** [comment]
@seriema oh, sorry, I just checked contributors :smile:

![image](https://cloud.githubusercontent.com/assets/775692/8812353/4791ee04-3004-11e5-90a5-7862614b4ca1.png)

About more specific: package's call is deprecated, as Atom said. When I'm trying Report issue, it redirect me to this issue.

**Comment by hax** [comment]
I will check it this weekend. :sweat_smile:

**Comment by hax** [comment]
I will release a new version soon.
