### ISSUE TITLE
Deprecated selector in `refactor\styles\refactor.less`

### ISSUE THREAD

**Issue by ismailarilik** [hax/refactor#36]
In `refactor\styles\refactor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .refactor-reference .region` => `atom-text-editor.editor .refactor-reference .region`

* `atom-text-editor::shadow .refactor-ref .region` => `atom-text-editor.editor .refactor-ref .region`

* `atom-text-editor::shadow .refactor-mut .region` => `atom-text-editor.editor .refactor-mut .region`

* `atom-text-editor::shadow .refactor-decl .region` => `atom-text-editor.editor .refactor-decl .region`

* `atom-text-editor::shadow .refactor-error .region` => `atom-text-editor.editor .refactor-error .region`

* `atom-text-editor::shadow .gutter .line-number.refactor-error .icon-right` => `atom-text-editor.editor .gutter .line-number.refactor-error .icon-right`

* `atom-text-editor::shadow .gutter .line-number.refactor-error .icon-right:before` => `atom-text-editor.editor .gutter .line-number.refactor-error .icon-right:before`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by hax** [comment]
PR is welcomed!

**Comment by RenaldasK** [comment]
First of all thanks a lot for your great work!

And second:
Will there be a new release coming out anytime soon with this fix?

**Comment by wattachai** [comment]
@hax Is there anything I can help on the new release to fix this issue?

**Comment by hax** [comment]
New version released.

**Comment by wattachai** [comment]
Deprecation warning is a past now. Cheers to @hax!
