### ISSUE TITLE
Cursor moves to top of document after finishing refactoring

### ISSUE THREAD

**Issue by hoonoh** [hax/refactor#46]
The cursor moves to the very top of the document (0:0) after refactoring has been done. For shorter documents which the whole area is displayed within screen height it shouldn't be too much of a problem but for longer codes, it is very frustrating to go back to where I have been editing last. (Most of time I try undo & redo again to move the cursor back to where I last edited)

Maybe this is caused from using combinations of plugins? I haven't investigated that far yet, but I can try if anyone guides me what to look for.

My main use of refactor plugin is for Javascript, so I also have js-refactor plugin installed.

**Comment by zaaack** [comment]
Same here.
