### ISSUE TITLE
So this plugin is dead and no longer supported?

### ISSUE THREAD

**Issue by machineghost** [hax/refactor#50]
Just verifying: it would seem from this https://github.com/hax/refactor/issues/45 (which shows the plug-in hasn't worked since April) that this project is dead.  I'll take a lack of response as confirmation ;)

**Comment by hax** [comment]
No, this plugin is not dead. And I always eat the dog food, so I can confirm both js-refactor and coffee-refactor still work on the recent Atom 1.19.x.
