### ISSUE TITLE
Warning for ?. when refactor is enabled

### ISSUE THREAD

**Issue by oliverhausler** [hax/refactor#53]
https://www.npmjs.com/package/@babel/plugin-proposal-optional-chaining

![image](https://user-images.githubusercontent.com/8090341/36950919-c26eb2c0-1fb1-11e8-8926-7700948b42b0.png)

**Comment by hax** [comment]
Could you provide me the warning message?

**Comment by hax** [comment]
Ok. I think it is because `?.` only available in babel 7. And the previous version of js-refactor are using babel 6. You could upgrade js-refactor package. If still problem, please submit issue to https://github.com/hax/js-refactor/issues

Thank you.
