### ISSUE TITLE
coffee-refactor has been **unpublished** from apm

### ISSUE THREAD

**Issue by harlantwood** [hax/refactor#6]
@minodisk said in a new issue ([This package is unpublished from apm now](https://github.com/minodisk/coffee-refactor/issues/9)): 

> I'm not using Atom now.
> You can fork and publish in apm.

Alerting here because you mention it in your instructions https://atom.io/packages/refactor -- and in case @hax or some other generous community member might like to take this on...

**Comment by hax** [comment]
~~Unfortunately we do not have maintainer for coffee-refactor now :crying_cat_face:.~~
https://github.com/Ragg-/coffee-refactor

**Comment by hax** [comment]
@Ragg- Could you change the settings of your repo to enable issue tracking?
